format_version: 3
pipelines:
  libhoney-yaml-config:
    lock_behavior: lockOnFailure
    group: WebJavaAPP
    materials:
      repo:
       git: https://github.com/devops-at06/OH_Libhoney_Webapp.git
       branch: master
    stages:
      - Compile:
          jobs:
            assemble:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - clean
                      - assemble
      - Test:
          jobs:
            unittests:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - clean
                      - test
              artifacts:
                - test:
                    source: build/test-results/test/*xml
                    destination: xml
            codeCoverage:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - clean
                      - test
                      - jacocoTestReport
                      - check
              artifacts:
                - build:
                    source: build/reports/coverage/*
                    destination: html_coverage
                - build:
                    source: build/reports/tests/test/*
                    destination: html_report
                - build:
                    source: build/reports/findbugs/main.html
                    destination: findbugs_html
                - build:
                    source: build/reports/findbugs/test.html
                    destination: findbugs_html
                - build:
                    source: build/reports/pmd/main.html
                    destination: pmd_html
                - build:
                    source: build/reports/pmd/test.html
                    destination: pmd_html
              tabs:
                Cod_Coverage: html_coverage/index.html
                Test_Summary: html_report/index.html
                Findbugs_main: findbugs_html/main.html
                Findbugs_test: findbugs_html/test.html
                PMD_main: pmd_html/main.html
                PMD_test: pmd_html/test.html
      - CodeQuality:
          jobs:
            sonarqube:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - sonarqube
                      - -Dsonar.organization=omar-limbert-github
                      - -Dsonar.host.url=https://sonarcloud.io
                      - -Dsonar.login=f005f31e1cc80c26275d54f377b35595a4457f86
      - Publish:
          jobs:
            pucblishArtifact:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - uploadArchives
              artifacts:
                - build:
                    source: repos/*.jar
                    destination: war
