format_version: 3
pipelines:
  libhoney-unittest:
    lock_behavior: lockOnFailure
    group: WebJavaAPP
    materials:
      repo:
       git: https://github.com/devops-at06/OH_Libhoney_Webapp.git
       branch: master
    stages:
      - Compile:
          jobs:
            assemble:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - clean
                      - assemble
      - Test:
          jobs:
            unittests:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - test
              artifacts:
                - test:
                    source: build/test-results/test/*xml
                    destination: xml
            codeCoverage:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - test
                      - jacocoTestReport
                      - check
              artifacts:
                - build:
                    source: build/reports/coverage/**/*
                    destination: html_coverage
                - build:
                    source: build/reports/tests/test/**/*
                    destination: html_report
                - build:
                    source: build/reports/findbugs/main.html
                    destination: findbugs_html
                - build:
                    source: build/reports/findbugs/test.html
                    destination: findbugs_html
                - build:
                    source: build/reports/pmd/main.html
                    destination: pmd_html
                - build:
                    source: build/reports/pmd/test.html
                    destination: pmd_html
              tabs:
                Cod_Coverage: html_coverage/index.html
                Test_Summary: html_report/index.html
                Findbugs_main: findbugs_html/main.html
                Findbugs_test: findbugs_html/test.html
                PMD_main: pmd_html/main.html
                PMD_test: pmd_html/test.html
      - CodeQuality:
          jobs:
            sonarqube:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - sonarqube
                      - -Dsonar.host.url=http://10.28.135.234:9000
      - Package:
          jobs:
            fatJar:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - build
                      - capsule
              artifacts:
                - build:
                    source: build/libs/*.jar
                    destination: fatJar
      - Publish:
          jobs:
            pucblishArtifact:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - uploadArchives
              artifacts:
                - build:
                    source: repos/*.jar
                    destination: war

      - Deploy:
          jobs:
            deploying:
              tasks:
                - fetch:
                     stage: Package
                     job: fatJar
                     source: fatJar/
                - exec:
                    command: ./gradlew
                    arguments:
                      - -b
                      - deploy.gradle
                      - deploy
                      - -Pdev_server=10.28.135.58 
                      - -Puser_server=ubuntu 
                      - -Pkey_path=/home/go/omy.pem 
                      - -Pjar_path=fatJar
                      - -Pjar_name=libhoney-java-example-webapp-1.0.2-capsule
                      - -Puser_home=/home/ubuntu
      - Acceptance:
          jobs:
            acceptance:
              tasks:
                - exec:
                    command: ./acceptance/gradlew
                    arguments:
                      - clean
                      - test
                      - cucumber
                      - allureReport
                      - -p
                      - acceptance
              artifacts:
                - build:
                    source: acceptance/build/allure-results/index.html
                    destination: allure_html
                - build:
                    source: acceptance/build/cucumber-results/*
                    destination: cucumber_html
              tabs:
                Allure_Report: allure_html/index.html
                Cucumber_Rep: cucumber_html/report-feature_gradle-cucumber-features-gradle-feature.html
                Cucumber_steps: cucumber_html/overview-steps.html
                Cucumber_ft: cucumber_html/overview-features.html
