require 'vagrant-openstack-provider'

Vagrant.configure("2") do |config|
  
  config.env.enable
  config.ssh.username = 'ubuntu'
  config.ssh.private_key_path = ENV['OS_KEY_PATH']
  
  config.vm.provider :openstack do |os, override|
    os.identity_api_version = ENV['OS_IDENTITY_API_VERSION'] 
    os.openstack_auth_url   = ENV['OS_AUTH_URL'] 
    os.username       = ENV['OS_USERNAME'] 
    os.password       = ENV['OS_PASSWORD'] 
    os.domain_name      = ENV['OS_DOMAIN_NAME'] 
    os.tenant_name      = ENV['OS_TENANT_NAME'] 
    os.project_name     = ENV['OS_PROJECT_NAME'] 
    os.keypair_name     = ENV['OS_KEY_PAIR_NAME'] 
  end
  
  config.vm.define 'linux-server-1' do |s| 
    s.vm.provider :openstack do |os, override|
      os.image        = ENV['OS_IMAGE'] 
      os.server_name = ENV['OS_VM_NAME']
      os.flavor = ENV['OS_FLAVOR'] 
      override.vm.synced_folder '.', '/vagrant', disabled: true
      end 
  end
  config.vm.provision "docker"
  config.vm.provision "docker_compose", compose_version: "1.21.2"
  
end